services:
  - type: web
    name: computervision-road-anomaly-detection
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1 